name: Build Game Images

on:
  workflow_call:
    inputs:
      build-items:
        required: true
        type: string

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-item: ${{ fromJson(inputs.build-items) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push public
        if: matrix.build-item.branch == 'public'
        uses: docker/build-push-action@v5
        with:
          context: ./build
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dontstarvetogether:public
            ${{ secrets.DOCKERHUB_USERNAME }}/dontstarvetogether:latest
          build-args: |
            DST_BRANCH=${{ matrix.build-item.branch }}
            DST_BUILDID=${{ matrix.build-item.buildid }}
            DST_TIMEUPDATED=${{ matrix.build-item.timeupdated }}

      - name: Build and push beta
        if: matrix.build-item.branch != 'public'
        uses: docker/build-push-action@v5
        with:
          context: ./build
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dontstarvetogether:${{ matrix.build-item.branch }}
          build-args: |
            DST_BRANCH=${{ matrix.build-item.branch }}
            DST_BUILDID=${{ matrix.build-item.buildid }}
            DST_TIMEUPDATED=${{ matrix.build-item.timeupdated }}
