name: Check and Update Game & Toolbox Images manually or every 30 Minutes

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  check-update:
    runs-on: ubuntu-latest
    outputs:
      changed-list: ${{ steps.get-changed-list.outputs.changed_list }}
      pushed: ${{ steps.commit-changes.outputs.pushed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Fetch game info
        id: fetch-game-info
        run: |
          max_retries=3
          retry_count=0
          success=false

          while [ $retry_count -lt $max_retries ] && [ "$success" = "false" ]; do
            retry_count=$((retry_count + 1))
            echo "::group::Attempt $retry_count of $max_retries"
            
            gameinfo=`curl -s "https://api.steamcmd.net/v1/info/343050"`
            if [ -z "$gameinfo" ]; then
              echo "(curl) Failed to fetch game info."
              echo "::endgroup::"
              if [ $retry_count -eq $max_retries ]; then
                exit 1
              fi
              sleep 5
              continue
            fi

            status=`echo $gameinfo | jq -r ".status"`
            data=`echo $gameinfo | jq -r ".data.\"343050\""`
            if [ "$status" = "failed" ] || [ "$data" = "{}" ]; then
              echo "(steamcmd) API request failed or returned empty data."
              echo "::endgroup::"
              if [ $retry_count -eq $max_retries ]; then
                exit 1
              fi
              sleep 5
              continue
            fi

            success=true
            echo "Successfully fetched game info on attempt $retry_count"
            echo "::endgroup::"
          done

          echo "gameinfo=$gameinfo" >> "$GITHUB_ENV"

          echo "::group::Game info"
          echo $gameinfo | jq
          echo "::endgroup::"

      - name: Get changed list
        id: get-changed-list
        run: |
          if [ -f version.csv ]; then
            previous=`cat version.csv | tail -n 1 | awk -F',' '{print $3}'`
          else
            previous=0
          fi

          current=`echo $gameinfo | jq -r ".data.\"343050\".depots.branches | to_entries[] | select(.value.pwdrequired != \"1\") | \"\\(.key),\\(.value.buildid),\\(.value.timeupdated)\"" | sort -t, -k3 -n | tail -n 1 | awk -F',' '{print $3}'`

          echo "::group::Timeupdated"
          echo "previous=$previous"
          echo "current=$current"
          echo "::endgroup::"

          changed_list=`echo $gameinfo | jq -cr ".data.\"343050\".depots.branches | to_entries | map({branch: .key} + .value) | map(select(.pwdrequired != \"1\" and .timeupdated > \"$previous\" and .timeupdated <= \"$current\"))"`
          echo "changed_list=$changed_list" >> "$GITHUB_OUTPUT"

          echo "::group::Changed list"
          echo $changed_list | jq
          echo "::endgroup::"

      - name: Update version csv
        run: |
          echo "branch,buildid,timeupdated" > version.csv
          csv_data=`echo $gameinfo | jq -r ".data.\"343050\".depots.branches | to_entries[] | select(.value.pwdrequired != \"1\") | \"\\(.key),\\(.value.buildid),\\(.value.timeupdated)\"" | sort -t, -k3 -n`
          echo "$csv_data" >> version.csv

          echo "::group::Version csv"
          cat version.csv
          echo "::endgroup::"

      - name: Commit changes
        id: commit-changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "update version csv"
          add: "version.csv"

  build-images:
    needs: check-update
    if: needs.check-update.outputs.changed-list != '[]' && needs.check-update.outputs.pushed == 'true'
    uses: ./.github/workflows/build.yml
    with:
      build-items: ${{ needs.check-update.outputs.changed-list }}
    secrets: inherit
