name: Update Don't Starve Together Image

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "bullseye/Dockerfile"
  schedule:
    - cron: "*/30 * * * *"

jobs:
  check-update:
    runs-on: ubuntu-latest
    outputs:
      pushed: ${{ steps.commit-changes.outputs.pushed }}
      versions: ${{ steps.get-versions.outputs.versions }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Fetch game versions
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends --no-install-suggests curl jq
          curl -s "https://api.steamcmd.net/v1/info/343050" | jq -r '.data."343050".depots.branches | to_entries[] | select(.value.pwdrequired != "1") | "\(.key) \(.value.buildid)"' | while read -r key value; do echo "$value" > "versions/${key}.txt"; done

      - name: Commit changes
        id: commit-changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Update version files"
          add: "versions/*.txt"

      - name: Get changed versions
        id: get-versions
        run: |
          echo "versions=$(git diff --name-only HEAD~1..HEAD -- 'versions/*.txt' | cut -d "/" -f 2 | cut -d "." -f 1 | jq -cnR '[inputs]')" >> "$GITHUB_OUTPUT"

  update-image:
    needs: check-update
    if: ${{ needs.check-update.outputs.pushed }} == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.check-update.outputs.versions) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./bullseye
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dontstarvetogether:${{ matrix.version }}
          build-args: BRANCH=${{ matrix.version }}

      - name: Build and push latest
        if: ${{ matrix.version }} == 'public'
        uses: docker/build-push-action@v5
        with:
          context: ./bullseye
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dontstarvetogether:latest
          build-args: BRANCH=${{ matrix.version }}
