name: Rebuild Game Images

on:
  workflow_dispatch:

jobs:
  get-rebuild-list:
    runs-on: ubuntu-20.04
    outputs:
      rebuild-list: ${{ steps.read-csv.outputs.rebuild_list }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Read Csv
        id: read-csv
        run: |
          if [ -f version.csv ]; then
            rebuild_list=`awk -F, 'NR > 1 {print "{\"branch\": \"" $1 "\", \"buildid\": \"" $2 "\", \"timeupdated\": \"" $3 "\"}"}' version.csv | jq -s '.'`
          else
            rebuild_list='[]'
          fi

          echo "rebuild_list=$rebuild_list" >> "$GITHUB_OUTPUT"

          echo "::group::Rebuild Branches"
          echo $rebuild_list | jq
          echo "::endgroup::"

  rebuild-image:
    needs: get-rebuild-list
    if: needs.get-rebuild-list.outputs.rebuild-list != '[]'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rebuild-item: ${{ fromJson(needs.get-rebuild-list.outputs.rebuild-list) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push public
        if: matrix.rebuild-item.branch == 'public'
        uses: docker/build-push-action@v5
        with:
          context: ./build
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dontstarvetogether:public
            ${{ secrets.DOCKERHUB_USERNAME }}/dontstarvetogether:latest
          build-args: |
            DST_BRANCH=${{ matrix.rebuild-item.branch }}
            DST_BUILDID=${{ matrix.rebuild-item.buildid }}
            DST_TIMEUPDATED=${{ matrix.rebuild-item.timeupdated }}

      - name: Build and push beta
        if: matrix.rebuild-item.branch != 'public'
        uses: docker/build-push-action@v5
        with:
          context: ./build
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dontstarvetogether:${{ matrix.rebuild-item.branch }}
          build-args: |
            DST_BRANCH=${{ matrix.rebuild-item.branch }}
            DST_BUILDID=${{ matrix.rebuild-item.buildid }}
            DST_TIMEUPDATED=${{ matrix.rebuild-item.timeupdated }}
